<a href="https://colab.research.google.com/github/ThummaBhanuteja/py/blob/master/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

In [19]:
import pandas as pd
path="/content/drive/MyDrive/Colab Notebooks/azocilin.csv"
df = pd.read_csv(path)
df.describe

<bound method NDFrame.describe of        Tc    Pc      w    M.W       T     S
0   512.6  80.9  0.556  32.04  278.15  2.81
1   512.6  80.9  0.556  32.04  283.15   3.3
2   512.6  80.9  0.556  32.04  288.15  4.03
3   512.6  80.9  0.556  32.04  293.15  4.78
4   512.6  80.9  0.556  32.04  298.15  6.02
..    ...   ...    ...    ...     ...   ...
85  508.1  47.0  0.304  58.08  303.15  11.2
86  508.1  47.0  0.304  58.08  308.15  13.3
87  508.1  47.0  0.304  58.08  313.15  15.5
88  508.1  47.0  0.304  58.08  318.15  19.2
89  508.1  47.0  0.304  58.08  323.15  22.3

[90 rows x 6 columns]>

In [20]:
import pandas as pd
import numpy as np
import tensorflow as tf
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/azocilin.csv")
df

       Tc    Pc      w    M.W       T     S
0   512.6  80.9  0.556  32.04  278.15  2.81
1   512.6  80.9  0.556  32.04  283.15   3.3
2   512.6  80.9  0.556  32.04  288.15  4.03
3   512.6  80.9  0.556  32.04  293.15  4.78
4   512.6  80.9  0.556  32.04  298.15  6.02
..    ...   ...    ...    ...     ...   ...
85  508.1  47.0  0.304  58.08  303.15  11.2
86  508.1  47.0  0.304  58.08  308.15  13.3
87  508.1  47.0  0.304  58.08  313.15  15.5
88  508.1  47.0  0.304  58.08  318.15  19.2
89  508.1  47.0  0.304  58.08  323.15  22.3

[90 rows x 6 columns]

# New section

In [21]:
X=df.iloc[:,:-1]
Y=df.iloc[:,[5]]
print(df.info())
print(Y)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Tc      90 non-null     float64
 1   Pc      90 non-null     float64
 2   w       90 non-null     float64
 3   M.W     90 non-null     float64
 4   T       90 non-null     float64
 5   S       90 non-null     object
dtypes: float64(5), object(1)
memory usage: 4.3+ KB
None
       S
0   2.81
1    3.3
2   4.03
3   4.78
4   6.02
..   ...
85  11.2
86  13.3
87  15.5
88  19.2
89  22.3

[90 rows x 1 columns]

In [28]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

from keras import models
from keras import layers
from keras import optimizers
X.shape, Y.shape

((90, 5), (90, 1))

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)
Y_train

       S
77  21.8
42  2.87
22  1.32
6   9.48
61  5.51
..   ...
86  13.3
67  12.2
64  8.36
47  5.28
44  3.53

[72 rows x 1 columns]

In [33]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
Y2=Y_test
Y1=Y_train
X2=X_test
X1=X_train
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)
Y_train

       S
77  21.8
42  2.87
22  1.32
6   9.48
61  5.51
..   ...
86  13.3
67  12.2
64  8.36
47  5.28
44  3.53

[72 rows x 1 columns]

In [38]:
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

model=Sequential()
model.add(Dense(5, input_dim=5, activation='relu'))
model.add(Dense(5,activation='relu'))


model.add(Dense(1,activation='linear'))


model.compile(loss='mean_squared_error',optimizer='RMSprop',metrics=['mae'])
model.summary()

history=model.fit(X_train,Y_train,validation_split=0.3,epochs=680)


from matplotlib import pyplot as plt

loss=history.history['loss']
val_loss=history.history['val_loss']
epochs=range(1,len(loss)+1)
plt.plot(epochs,loss,'y',label='Traiing loss')
plt.plot(epochs,val_loss,'r',label='Validation loss')
plt.title('Training and Validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_30 (Dense)            (None, 5)                 30

 dense_31 (Dense)            (None, 5)                 30

 dense_32 (Dense)            (None, 1)                 6

=================================================================
Total params: 66
Trainable params: 66
Non-trainable params: 0
_________________________________________________________________
Epoch 1/680

UnimplementedError: ignored

Epoch 1/50

ValueError: ignored

# New section